#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${AUTH_POSTGRES_USER} WITH PASSWORD '${AUTH_POSTGRES_PASSWORD}';
    CREATE DATABASE ${AUTH_POSTGRES_DB} OWNER ${AUTH_POSTGRES_USER};

    CREATE USER ${CINEMA_POSTGRES_USER} WITH PASSWORD '${CINEMA_POSTGRES_PASSWORD}';
    CREATE DATABASE ${CINEMA_POSTGRES_DB} OWNER ${CINEMA_POSTGRES_USER};
EOSQL
