# Generated by Django 5.2.5 on 2025-08-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
