[tool.mypy]
python_version = 3.13
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disable_error_code = "misc"
exclude = "(.*alembic/.*$|.*meta_classes\\.py$|admin_service/cinema/migrations/.*$|admin_service/manage.py)"

[tool.flake8]
ignore = "E203"
extend-ignore = "W503, B008"
exclude = "*/alembic/*, */meta_classes.py, .venv, .git, __pycache__"
